// Auto-generated Phase 2 registry — driver experience
import type { PolicyRecord } from '@/lib/navigationPolicy/types';

export const DRIVER_POLICIES: readonly PolicyRecord[] = [
  {
    id: 'driver.home',
    pattern: '/(driver)',
    experience: 'driver',
    priority: 100,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.wallet',
    pattern: '/(driver)/wallet',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.stories',
    pattern: '/(driver)/stories',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.chat',
    pattern: '/(driver)/chat',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.control',
    pattern: '/(driver)/control',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.documents',
    pattern: '/(driver)/documents',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.level-progression',
    pattern: '/(driver)/level-progression',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.notifications',
    pattern: '/(driver)/notifications',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.pending-earnings',
    pattern: '/(driver)/pending-earnings',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.profile',
    pattern: '/(driver)/profile',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.requests',
    pattern: '/(driver)/requests',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.settings',
    pattern: '/(driver)/settings',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.passbook-history',
    pattern: '/(driver)/passbook/history',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.passbook-org',
    pattern: '/(driver)/passbook/:orgId',
    experience: 'driver',
    priority: 80,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.salary-request',
    pattern: '/(driver)/salary-request',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.salary-request-id',
    pattern: '/(driver)/salary-request/:id',
    experience: 'driver',
    priority: 80,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.trip-history',
    pattern: '/(driver)/trip-history',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    // Moved out of (driver) to a root-level route (app/driver-trip/[tripId])
    // so Trip Detail renders outside the driver Tabs -- pattern updated to
    // match; this is now the sole access-control boundary for that screen
    // (previously also covered by (driver)/_layout.tsx's own inline gate,
    // which no longer applies since the route left that tree).
    id: 'driver.trip-detail',
    pattern: '/driver-trip/:tripId',
    experience: 'driver',
    priority: 80,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.expense-capture',
    pattern: '/(driver)/expense-capture',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.general-expense',
    pattern: '/(driver)/general-expense',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.dco-status',
    pattern: '/(driver)/dco-status',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.my-fleet',
    pattern: '/(driver)/my-fleet',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.my-fleet-add',
    pattern: '/(driver)/my-fleet/add',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.my-fleet-vehicle',
    pattern: '/(driver)/my-fleet/:vehicleId',
    experience: 'driver',
    priority: 80,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.available-loads',
    pattern: '/(driver)/available-loads',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.available-load',
    pattern: '/(driver)/available-loads/:indentId',
    experience: 'driver',
    priority: 80,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
  {
    id: 'driver.capacity-story',
    pattern: '/(driver)/capacity-story',
    experience: 'driver',
    priority: 90,
    onDeny: { type: 'experience_home', experience: 'driver' },
  },
];
