// Auto-generated Phase 2 registry — org experience
import type { PolicyRecord } from '@/lib/navigationPolicy/types';

export const ORG_POLICIES: readonly PolicyRecord[] = [
  {
    id: 'org.trips',
    pattern: '/trips',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.finance',
    pattern: '/finance',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.resources',
    pattern: '/resources',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.clients',
    pattern: '/clients',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.network',
    pattern: '/network',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.network-hub',
    pattern: '/network/hub',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.profile',
    pattern: '/profile',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.payment-detail',
    pattern: '/payment-detail',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.report',
    pattern: '/report',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.indents-alias',
    pattern: '/indents',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'path', path: '/pulse-loads' },
    softDeny: true,
  },
  {
    id: 'org.pulse-loads',
    pattern: '/pulse-loads',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  // Trip Compliance + Finance settlement — coarse org-capability gate only
  // (must be a dispatch org for Compliance to be meaningful at all); the real
  // enable/disable (workspace_products.pulse_compliance) and fine-grained
  // RBAC (trip_compliance.* MemberSurfaceId) checks happen in-screen, per
  // "Navigation ≠ Authorization" above.
  {
    id: 'org.compliance',
    pattern: '/compliance',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.compliance-bulk-payment',
    pattern: '/compliance/bulk-payment',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_manage'] },
    onDeny: { type: 'path', path: '/compliance' },
    softDeny: true,
  },
  {
    id: 'org.compliance-report',
    pattern: '/compliance/report',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/compliance' },
    softDeny: true,
  },
  {
    // A4.3: same gate as Load Center for this first version (see
    // docs/MARKETPLACE_DOMAIN.md "Distribution vs monetization" — discovery
    // is membership-only in principle; this route-level gate is an MVP
    // simplification, not a new capability).
    id: 'org.find-loads',
    pattern: '/find-loads',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.create-indent',
    pattern: '/create-indent',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['dispatch'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.load-board',
    pattern: '/load-board',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.add-trip',
    pattern: '/add-trip',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.indent',
    pattern: '/indent/:id',
    experience: 'org',
    priority: 80,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.indent-allocation',
    pattern: '/indent/:id/allocation',
    experience: 'org',
    priority: 90,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.client',
    pattern: '/client/:id',
    experience: 'org',
    priority: 80,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.client-analytics',
    pattern: '/client/:id/analytics',
    experience: 'org',
    priority: 90,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.client-profile',
    pattern: '/client/:id/profile',
    experience: 'org',
    priority: 90,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.supplier',
    pattern: '/supplier/:id',
    experience: 'org',
    priority: 80,
    grants: { anyOf: ['dispatch'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.supplier-analytics',
    pattern: '/supplier/:id/analytics',
    experience: 'org',
    priority: 90,
    grants: { anyOf: ['dispatch'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.supplier-profile',
    pattern: '/supplier/:id/profile',
    experience: 'org',
    priority: 90,
    grants: { anyOf: ['dispatch'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.party-customers-id',
    pattern: '/party/customers/:id',
    experience: 'org',
    priority: 95,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.party-suppliers',
    pattern: '/party/suppliers',
    experience: 'org',
    priority: 95,
    grants: { anyOf: ['dispatch'] },
    onDeny: { type: 'path', path: '/party/customers' },
    softDeny: true,
  },
  {
    id: 'org.party-vehicles',
    pattern: '/party/vehicles',
    experience: 'org',
    priority: 95,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/party/customers' },
    softDeny: true,
  },
  {
    id: 'org.party-drivers',
    pattern: '/party/drivers',
    experience: 'org',
    priority: 95,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/party/customers' },
    softDeny: true,
  },
  {
    id: 'org.party-customers',
    pattern: '/party/customers',
    experience: 'org',
    priority: 95,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.party-kind',
    pattern: '/party/:kind',
    experience: 'org',
    priority: 70,
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.driver-entity',
    pattern: '/driver/:id',
    experience: 'org',
    priority: 80,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.driver-analytics',
    pattern: '/driver/:id/analytics',
    experience: 'org',
    priority: 90,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.driver-profile',
    pattern: '/driver/:id/profile',
    experience: 'org',
    priority: 90,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.vehicle',
    pattern: '/vehicle/:id',
    experience: 'org',
    priority: 80,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.vehicle-analytics',
    pattern: '/vehicle/:id/analytics',
    experience: 'org',
    priority: 90,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.vehicle-profile',
    pattern: '/vehicle/:id/profile',
    experience: 'org',
    priority: 90,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.trip',
    pattern: '/trip/:id',
    experience: 'org',
    priority: 70,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-track-trace',
    pattern: '/track/:tripId',
    experience: 'org',
    priority: 70,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.fleet-operations',
    pattern: '/fleet-operations',
    experience: 'org',
    priority: 70,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-assignment',
    pattern: '/trip/:id/assignment',
    experience: 'org',
    priority: 90,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-verification',
    pattern: '/trip/:id/verification',
    // Driver Operations + office trip detail both open this stack.
    experience: 'shared',
    priority: 90,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-ops-expenses',
    pattern: '/trip/:id/operations/expenses',
    experience: 'shared',
    priority: 90,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-ops-fuel',
    pattern: '/trip/:id/operations/fuel',
    experience: 'shared',
    priority: 90,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-ops-toll',
    pattern: '/trip/:id/operations/toll',
    experience: 'shared',
    priority: 90,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-ops-other',
    pattern: '/trip/:id/operations/other',
    experience: 'shared',
    priority: 90,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-ops-launcher',
    pattern: '/trip/:id/operations/launcher',
    experience: 'shared',
    priority: 90,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.finance-entry',
    pattern: '/finance-entry/:id',
    experience: 'org',
    priority: 80,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.trip-ledger',
    pattern: '/trip-ledger/:id',
    experience: 'org',
    priority: 80,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.invoicing-pdf',
    pattern: '/invoicing/pdf-preview',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.invoicing-execute',
    pattern: '/invoicing-execute',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.invoicing-execute-create',
    pattern: '/invoicing-execute/create',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.invoicing-execute-order',
    pattern: '/invoicing-execute/order/:orderId',
    experience: 'org',
    priority: 110,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.invoicing-execute-manual',
    pattern: '/invoicing-execute/manual',
    experience: 'org',
    priority: 110,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.ledger-sync',
    pattern: '/ledger-sync',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.workspace',
    pattern: '/workspace',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.documents-center',
    pattern: '/documents-center',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.notifications',
    pattern: '/notifications',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.chat',
    pattern: '/chat',
    experience: 'org',
    // Operating-model floor only. Per-member `sales.chat` is enforced in the
    // route itself — this grant set is org capabilities, not member surfaces.
    grants: {
      anyOf: [
        'dispatch',
        'dispatch_for_own_fleet',
        'marketplace_post',
        'marketplace_bid',
      ],
    },
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.alert-detail',
    pattern: '/alert-detail',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.milestone',
    pattern: '/milestone',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.network-user',
    pattern: '/network-user',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.pod-reconciliation',
    pattern: '/pod-reconciliation',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.finance-pro',
    pattern: '/finance-pro',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.finance-pro-receivables',
    pattern: '/finance-pro/receivables',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.finance-pro-trips-pod',
    pattern: '/finance-pro/trips-pod',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.finance-pro-invoices',
    pattern: '/finance-pro/invoices',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.finance-pro-payments',
    pattern: '/finance-pro/payments',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.finance-pro-analytics',
    pattern: '/finance-pro/analytics',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.finance-pro-client',
    pattern: '/finance-pro/client/:id',
    experience: 'org',
    priority: 110,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.finance-pro-invoice-doc',
    pattern: '/finance-pro/invoice/:id',
    experience: 'org',
    priority: 110,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.finance-pro-trip',
    pattern: '/finance-pro/trip/:id',
    experience: 'org',
    priority: 110,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.finance-pro-cash',
    pattern: '/finance-pro/cash/:id',
    experience: 'org',
    priority: 110,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.pulse-invoice',
    pattern: '/pulse-invoice',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.pulse-invoice-pod',
    pattern: '/pulse-invoice/pod',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.pulse-invoice-order',
    pattern: '/pulse-invoice/order/:orderId',
    experience: 'org',
    priority: 110,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.pulse-invoice-manual',
    pattern: '/pulse-invoice/manual',
    experience: 'org',
    priority: 110,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.log-incoming-pods',
    pattern: '/log-incoming-pods',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.debit-control',
    pattern: '/debit-control',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.add-commodity-type',
    pattern: '/add-commodity-type',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.support',
    pattern: '/support',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.support-tickets',
    pattern: '/support-tickets',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.support-ticket-detail',
    pattern: '/support-ticket/:id',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal',
    pattern: '/modal',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.audit',
    pattern: '/audit',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.audit-log',
    pattern: '/audit-log',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-add-client',
    pattern: '/add-client',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.modal-edit-client',
    pattern: '/edit-client',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.modal-add-supplier',
    pattern: '/add-supplier',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['dispatch'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.modal-attribution',
    pattern: '/attribution-trip-create',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.modal-add-driver',
    pattern: '/add-driver',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.modal-add-vehicle',
    pattern: '/add-vehicle',
    experience: 'org',
    priority: 100,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.modal-team',
    pattern: '/team',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-access-control',
    pattern: '/access-control',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-member-permissions',
    pattern: '/member-permissions',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-invite',
    pattern: '/invite-member',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-language',
    pattern: '/language-settings',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-create-post',
    pattern: '/create-post',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-post-detail',
    pattern: '/post-detail',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-story-detail',
    pattern: '/story-detail',
    // Public share link + driver/org viewers. Route gate handles sales grant
    // and driver Pulse preview branch.
    experience: 'public_content',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.reach-home',
    pattern: '/reach',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.reach-history',
    pattern: '/reach/history',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.reach-earn-credits',
    pattern: '/reach/earn-credits',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.reach-inbox',
    pattern: '/reach/inbox',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.reach-campaign-detail',
    pattern: '/reach/campaign/:id',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-sms-otp',
    pattern: '/sms-otp-parsing',
    experience: 'org',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
];
